name: fusion_new
description: A Flutter fitness tracking app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^0.13.6
  image_picker: ^1.1.2
  fl_chart: ^0.66.0
  provider: ^6.1.1
  english_words: ^4.0.0
  url_launcher: ^6.3.0
  flutter_rating_bar: ^4.0.1
  mailer: ^6.5.0
  health: ^13.2.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  flutter_gen: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/hsp.png
    - assets/images/logo.png
    - assets/images/Bewegung.png
    - assets/images/Frisbee.png
    - assets/images/Klingeling.png
    - assets/images/Liegestuhl.png
    - assets/images/Tasche.png